// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxx5Hrnt6ch84-rqpzsLIVHrJI5juGoSk',
    appId: '1:86213463067:web:de84adbedafc0115413cbe',
    messagingSenderId: '86213463067',
    projectId: 'ahsan-f81b8',
    authDomain: 'ahsan-f81b8.firebaseapp.com',
    storageBucket: 'ahsan-f81b8.appspot.com',
    measurementId: 'G-GB1W2YWZ3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBT5rO03OcjzxXFei2fGAjb1GzLhn2oNc',
    appId: '1:86213463067:android:08d38447f326735e413cbe',
    messagingSenderId: '86213463067',
    projectId: 'ahsan-f81b8',
    storageBucket: 'ahsan-f81b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7BBPDLuhji8Uc-I6s6E4IK8X2vfDM1IA',
    appId: '1:86213463067:ios:46cc3def583166ca413cbe',
    messagingSenderId: '86213463067',
    projectId: 'ahsan-f81b8',
    storageBucket: 'ahsan-f81b8.appspot.com',
    iosBundleId: 'com.ahsant.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7BBPDLuhji8Uc-I6s6E4IK8X2vfDM1IA',
    appId: '1:86213463067:ios:46cc3def583166ca413cbe',
    messagingSenderId: '86213463067',
    projectId: 'ahsan-f81b8',
    storageBucket: 'ahsan-f81b8.appspot.com',
    iosBundleId: 'com.ahsant.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxx5Hrnt6ch84-rqpzsLIVHrJI5juGoSk',
    appId: '1:86213463067:web:403d4cccf173c078413cbe',
    messagingSenderId: '86213463067',
    projectId: 'ahsan-f81b8',
    authDomain: 'ahsan-f81b8.firebaseapp.com',
    storageBucket: 'ahsan-f81b8.appspot.com',
    measurementId: 'G-MMYVP6B4YM',
  );

}